"""empty message

Revision ID: 9c7337ebbd77
Revises: 987ae7978f32
Create Date: 2024-09-15 18:46:27.219475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7337ebbd77'
down_revision: Union[str, None] = '987ae7978f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('id_task', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'tasks', ['id_task'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'id_task')
    # ### end Alembic commands ###
